"""
additional_schemes.py — Adds 125+ additional genuine Government of India and State Government
schemes to the BharatSeva AI database.

Sources: Official Government websites, MyScheme portal (myscheme.gov.in),
         National Informatics Centre scheme data, and state government portals.

Run: python additional_schemes.py (from /backend)
"""
from __future__ import annotations

import json
import logging
import uuid
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _uuid() -> str:
    return str(uuid.uuid4())


def _docs(*names) -> str:
    return json.dumps([{"name": n, "mandatory": True} for n in names])


def _rules(**kwargs) -> str:
    rules = []
    for field, val in kwargs.items():
        if field == "category":
            rules.append({"field": "category", "operator": "in", "values": [val] if isinstance(val, str) else val})
        elif field == "occupation":
            rules.append({"field": "occupation", "operator": "in", "values": [val] if isinstance(val, str) else val})
        elif field == "gender":
            rules.append({"field": "gender", "operator": "eq", "value": val})
        elif field == "max_income":
            rules.append({"field": "annual_income", "operator": "lte", "value": val})
        elif field == "min_age":
            rules.append({"field": "age", "operator": "gte", "value": val})
        elif field == "max_age":
            rules.append({"field": "age", "operator": "lte", "value": val})
    return json.dumps({"logic": "AND", "rules": rules})


ADDITIONAL_SCHEMES = [

    # ── FINANCIAL INCLUSION ──────────────────────────────────────────────────
    {
        "name": "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
        "name_hi": "प्रधानमंत्री जन धन योजना",
        "category": "financial_inclusion",
        "state_or_all_india": "ALL_INDIA",
        "description": "World's largest financial inclusion programme providing universal access to banking, insurance, and pension. Zero-balance savings accounts with RuPay debit card, ₹1 lakh accident insurance, ₹30,000 life insurance, and ₹10,000 overdraft facility.",
        "eligibility_rules_json": _rules(min_age=18),
        "required_documents_json": _docs("Aadhaar Card", "Passport-size photograph"),
        "application_url": "https://pmjdy.gov.in",
        "deadline": None,
        "source_name": "PMJDY Official Portal",
        "source_url": "https://pmjdy.gov.in",
        "last_verified_date": "2025-06-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Nearest bank branch or BC point",
        "office_contact": "1800-11-0001",
    },
    {
        "name": "Atal Pension Yojana (APY)",
        "name_hi": "अटल पेंशन योजना",
        "category": "financial_inclusion",
        "state_or_all_india": "ALL_INDIA",
        "description": "Government-backed pension scheme for unorganised sector workers. Guaranteed monthly pension of ₹1,000–₹5,000 after age 60. Government co-contributes 50% of subscriber's contribution or ₹1,000/year (whichever is lower) for first 5 years for non-income-tax payers.",
        "eligibility_rules_json": _rules(min_age=18, max_age=40),
        "required_documents_json": _docs("Aadhaar Card", "Bank account with mobile number", "Savings bank account"),
        "application_url": "https://npscra.nsdl.co.in",
        "deadline": None,
        "source_name": "PFRDA Atal Pension Yojana",
        "source_url": "https://npscra.nsdl.co.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Nearest bank branch or CSC",
        "office_contact": "1800-110-069",
    },
    {
        "name": "National Pension System (NPS) — Swavalamban",
        "name_hi": "राष्ट्रीय पेंशन प्रणाली",
        "category": "financial_inclusion",
        "state_or_all_india": "ALL_INDIA",
        "description": "Voluntary pension scheme with market-linked returns. Government contributes ₹1,000/year for low-income subscribers. Tax benefits under Section 80CCD. Allows choice of pension fund managers.",
        "eligibility_rules_json": _rules(min_age=18, max_age=70),
        "required_documents_json": _docs("Aadhaar Card", "PAN Card", "Bank account details", "Passport-size photograph"),
        "application_url": "https://enps.nsdl.com",
        "deadline": None,
        "source_name": "PFRDA NPS",
        "source_url": "https://www.pfrda.org.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "PFRDA, Chatrapati Shivaji Bhawan, New Delhi",
        "office_contact": "1800-110-069",
    },

    # ── HEALTH ──────────────────────────────────────────────────────────────
    {
        "name": "Ayushman Bharat — PM Jan Arogya Yojana (PM-JAY)",
        "name_hi": "आयुष्मान भारत — प्रधानमंत्री जन आरोग्य योजना",
        "category": "health",
        "state_or_all_india": "ALL_INDIA",
        "description": "World's largest publicly funded health insurance scheme providing ₹5 lakh per family per year for secondary and tertiary hospitalisation. Covers 1,929 medical procedures across 24 specialties. Cashless treatment at 27,000+ empanelled hospitals.",
        "eligibility_rules_json": _rules(max_income=200000),
        "required_documents_json": _docs("Aadhaar Card", "PM-JAY eligibility letter or e-card", "Ration card (for SECC identification)"),
        "application_url": "https://pmjay.gov.in",
        "deadline": None,
        "source_name": "Ayushman Bharat PM-JAY",
        "source_url": "https://pmjay.gov.in",
        "last_verified_date": "2025-06-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "National Health Authority, New Delhi",
        "office_contact": "14555",
    },
    {
        "name": "Janani Suraksha Yojana (JSY)",
        "name_hi": "जननी सुरक्षा योजना",
        "category": "health",
        "state_or_all_india": "ALL_INDIA",
        "description": "Cash assistance to pregnant women for institutional delivery. LPS (Low Performance States) rural: ₹1,400; urban: ₹1,000. HPS (High Performance States) rural: ₹700; urban: ₹600. ASHA worker incentive: ₹600 rural, ₹200 urban.",
        "eligibility_rules_json": _rules(gender="female"),
        "required_documents_json": _docs("Aadhaar Card", "Ante-natal care card", "BPL card or below-poverty line proof", "Bank account details"),
        "application_url": "https://nhm.gov.in/index1.php?lang=1&level=3&sublinkid=841&lid=309",
        "deadline": None,
        "source_name": "National Health Mission",
        "source_url": "https://nhm.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Nearest government health centre / ASHA worker",
        "office_contact": "1800-180-1104",
    },
    {
        "name": "Rashtriya Swasthya Bima Yojana (RSBY)",
        "name_hi": "राष्ट्रीय स्वास्थ्य बीमा योजना",
        "category": "health",
        "state_or_all_india": "ALL_INDIA",
        "description": "Smart card-based cashless health insurance for BPL families. Cover of ₹30,000 per family per year. Covers hospitalisation, pre-existing diseases from day 1. Family of up to 5 members.",
        "eligibility_rules_json": _rules(max_income=100000),
        "required_documents_json": _docs("BPL ration card", "Aadhaar Card", "Passport-size photographs"),
        "application_url": "https://www.rsby.gov.in",
        "deadline": None,
        "source_name": "Ministry of Labour & Employment",
        "source_url": "https://www.rsby.gov.in",
        "last_verified_date": "2025-03-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Collectorate / Labour Department",
        "office_contact": "011-23381747",
    },

    # ── HOUSING ──────────────────────────────────────────────────────────────
    {
        "name": "Pradhan Mantri Awas Yojana — Gramin (PMAY-G)",
        "name_hi": "प्रधानमंत्री आवास योजना — ग्रामीण",
        "category": "housing",
        "state_or_all_india": "ALL_INDIA",
        "description": "Provides financial assistance to BPL households in rural areas for construction of pucca houses. ₹1.20 lakh in plain areas and ₹1.30 lakh in hilly/difficult areas. Convergence with MGNREGS for 90/95 days unskilled labour.",
        "eligibility_rules_json": _rules(max_income=150000),
        "required_documents_json": _docs("Aadhaar Card", "BPL card or SECC data", "Bank account (Aadhaar-linked)", "Land ownership document or NOC"),
        "application_url": "https://pmayg.nic.in",
        "deadline": "2026-03-31",
        "source_name": "PMAY-G Official Portal",
        "source_url": "https://pmayg.nic.in",
        "last_verified_date": "2025-06-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Block Development Office / Gram Panchayat",
        "office_contact": "1800-11-6446",
    },
    {
        "name": "Pradhan Mantri Awas Yojana — Urban (PMAY-U)",
        "name_hi": "प्रधानमंत्री आवास योजना — शहरी",
        "category": "housing",
        "state_or_all_india": "ALL_INDIA",
        "description": "Credit Linked Subsidy Scheme (CLSS) for urban housing. EWS/LIG: 6.5% interest subsidy on loans up to ₹6 lakh. MIG-I: 4% on ₹9 lakh. MIG-II: 3% on ₹12 lakh. Also covers in-situ slum rehabilitation and affordable housing.",
        "eligibility_rules_json": _rules(max_income=1800000),
        "required_documents_json": _docs("Aadhaar Card", "Income certificate", "Property documents", "Bank statements (6 months)", "PAN Card"),
        "application_url": "https://pmaymis.gov.in",
        "deadline": "2026-03-31",
        "source_name": "PMAY-U Official Portal",
        "source_url": "https://pmaymis.gov.in",
        "last_verified_date": "2025-06-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Urban Local Body / Municipality",
        "office_contact": "1800-11-3377",
    },
    {
        "name": "PM Surya Ghar — Muft Bijli Yojana",
        "name_hi": "पीएम सूर्य घर — मुफ्त बिजली योजना",
        "category": "housing",
        "state_or_all_india": "ALL_INDIA",
        "description": "Provides free electricity up to 300 units/month through rooftop solar panels. Subsidy: 60% for 1-2 kW systems; 40% additional for 2-3 kW. Target: 1 crore households. Net metering allows selling surplus power to grid.",
        "eligibility_rules_json": _rules(min_age=18),
        "required_documents_json": _docs("Aadhaar Card", "Electricity consumer number / bill", "Bank account", "Rooftop ownership proof"),
        "application_url": "https://pmsuryaghar.gov.in",
        "deadline": "2027-03-31",
        "source_name": "PM Surya Ghar Portal",
        "source_url": "https://pmsuryaghar.gov.in",
        "last_verified_date": "2025-06-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Nearest electricity distribution company (DISCOM)",
        "office_contact": "1800-180-3333",
    },

    # ── LPG / ENERGY ─────────────────────────────────────────────────────────
    {
        "name": "Pradhan Mantri Ujjwala Yojana (PMUY)",
        "name_hi": "प्रधानमंत्री उज्ज्वला योजना",
        "category": "energy",
        "state_or_all_india": "ALL_INDIA",
        "description": "Provides free LPG connections to women from BPL households to reduce indoor air pollution and improve health. Includes free first refill and hotplate. EMI facility for initial cost recovery.",
        "eligibility_rules_json": _rules(gender="female", max_income=100000),
        "required_documents_json": _docs("Aadhaar Card", "BPL ration card", "Bank passbook", "Passport-size photograph"),
        "application_url": "https://www.pmuy.gov.in",
        "deadline": None,
        "source_name": "PMUY Official Portal",
        "source_url": "https://www.pmuy.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Nearest LPG distributor or CSC",
        "office_contact": "1800-2333-555",
    },

    # ── WOMEN EMPOWERMENT ────────────────────────────────────────────────────
    {
        "name": "Beti Bachao Beti Padhao (BBBP)",
        "name_hi": "बेटी बचाओ बेटी पढ़ाओ",
        "category": "women",
        "state_or_all_india": "ALL_INDIA",
        "description": "Multi-sectoral programme to address declining Child Sex Ratio and promote education of girl child. Includes 100% sukanya samriddhi account deposits, conditional cash transfers for girl education, and awareness campaigns.",
        "eligibility_rules_json": _rules(gender="female"),
        "required_documents_json": _docs("Birth certificate of girl child", "Parents' Aadhaar Card", "Bank account"),
        "application_url": "https://wcd.nic.in",
        "deadline": None,
        "source_name": "Ministry of Women and Child Development",
        "source_url": "https://wcd.nic.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Women and Child Development Office",
        "office_contact": "011-23381611",
    },
    {
        "name": "Sukanya Samriddhi Yojana (SSY)",
        "name_hi": "सुकन्या समृद्धि योजना",
        "category": "women",
        "state_or_all_india": "ALL_INDIA",
        "description": "Small savings scheme for girl child under BBBP initiative. Current interest rate: 8.2% p.a. (compounded annually). Account can be opened for girl below 10 years. Minimum deposit: ₹250/year, Maximum: ₹1.5 lakh/year. Tax benefit under 80C.",
        "eligibility_rules_json": _rules(gender="female", max_age=10),
        "required_documents_json": _docs("Girl child's birth certificate", "Parent/guardian's Aadhaar Card", "PAN Card (optional)", "Passport-size photograph"),
        "application_url": "https://www.india.gov.in/sukanya-samriddhi-yojna",
        "deadline": None,
        "source_name": "Ministry of Finance — Sukanya Samriddhi",
        "source_url": "https://www.nsiindia.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Nearest post office or authorised bank",
        "office_contact": "1800-11-2011",
    },
    {
        "name": "Mahila Shakti Kendra (MSK)",
        "name_hi": "महिला शक्ति केंद्र",
        "category": "women",
        "state_or_all_india": "ALL_INDIA",
        "description": "One-stop convergence support service for rural women at village, block, district, and state levels. Provides skill training, digital literacy, legal awareness, nutrition and health awareness, and connects women with government schemes.",
        "eligibility_rules_json": _rules(gender="female"),
        "required_documents_json": _docs("Aadhaar Card", "Residence proof"),
        "application_url": "https://wcd.nic.in/schemes/mahila-shakti-kendra",
        "deadline": None,
        "source_name": "MoWCD",
        "source_url": "https://wcd.nic.in",
        "last_verified_date": "2025-03-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Block-level Mahila Shakti Kendra",
        "office_contact": "011-23381611",
    },

    # ── AGRICULTURE ──────────────────────────────────────────────────────────
    {
        "name": "Pradhan Mantri Krishi Sinchai Yojana (PMKSY)",
        "name_hi": "प्रधानमंत्री कृषि सिंचाई योजना",
        "category": "farmer",
        "state_or_all_india": "ALL_INDIA",
        "description": "Micro-irrigation scheme to ensure 'More crop per drop'. Drip/sprinkler irrigation with 55% central subsidy and additional state subsidy. Covers installation cost of irrigation equipment for small and marginal farmers.",
        "eligibility_rules_json": _rules(occupation="farmer"),
        "required_documents_json": _docs("Aadhaar Card", "Land records (Khasra/Khatoni)", "Bank account passbook", "Soil health card"),
        "application_url": "https://pmksy.gov.in",
        "deadline": None,
        "source_name": "PMKSY Official Portal",
        "source_url": "https://pmksy.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Agriculture Officer",
        "office_contact": "011-23382012",
    },
    {
        "name": "eNAM — National Agriculture Market",
        "name_hi": "ई-नाम — राष्ट्रीय कृषि बाजार",
        "category": "farmer",
        "state_or_all_india": "ALL_INDIA",
        "description": "Online trading platform linking APMCs across India. Farmers get better price discovery, transparent auction, and direct payment. 585+ mandis integrated. Payment within 24 hours of sale.",
        "eligibility_rules_json": _rules(occupation="farmer"),
        "required_documents_json": _docs("Aadhaar Card", "Bank account details", "Land records"),
        "application_url": "https://enam.gov.in",
        "deadline": None,
        "source_name": "eNAM Official Portal",
        "source_url": "https://enam.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Nearest APMC / Mandi",
        "office_contact": "1800-270-0224",
    },
    {
        "name": "Soil Health Card Scheme",
        "name_hi": "मृदा स्वास्थ्य कार्ड योजना",
        "category": "farmer",
        "state_or_all_india": "ALL_INDIA",
        "description": "Provides soil nutrient status to farmers and recommends appropriate dosage of nutrients. Issued every 2 years. Helps reduce input costs and increase productivity. Covers NPK, pH, EC, OC, and 8 micro-nutrients.",
        "eligibility_rules_json": _rules(occupation="farmer"),
        "required_documents_json": _docs("Aadhaar Card", "Land records"),
        "application_url": "https://soilhealth.dac.gov.in",
        "deadline": None,
        "source_name": "Soil Health Portal",
        "source_url": "https://soilhealth.dac.gov.in",
        "last_verified_date": "2025-03-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Agriculture Office / Village Level Worker",
        "office_contact": "011-23382640",
    },

    # ── EMPLOYMENT / SKILL ────────────────────────────────────────────────────
    {
        "name": "PM Vishwakarma Yojana",
        "name_hi": "पीएम विश्वकर्मा योजना",
        "category": "skill",
        "state_or_all_india": "ALL_INDIA",
        "description": "Support to 18 traditional artisan/craftsmen families (kaarigars). ₹15,000 toolkit incentive, credit at 5% interest (up to ₹3 lakh), skill training with ₹500/day stipend, and PM Vishwakarma certificate and ID card.",
        "eligibility_rules_json": _rules(occupation=["artisan", "craftsman"]),
        "required_documents_json": _docs("Aadhaar Card", "Caste certificate (if applicable)", "Bank account", "Ration card"),
        "application_url": "https://pmvishwakarma.gov.in",
        "deadline": None,
        "source_name": "PM Vishwakarma Portal",
        "source_url": "https://pmvishwakarma.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Common Service Centre (CSC) / District Industries Centre",
        "office_contact": "18001803000",
    },
    {
        "name": "Pradhan Mantri Kaushal Vikas Yojana (PMKVY)",
        "name_hi": "प्रधानमंत्री कौशल विकास योजना",
        "category": "skill",
        "state_or_all_india": "ALL_INDIA",
        "description": "Skill certification scheme enabling Indian youth to take up industry-relevant skill training. Short-term training: free, with certification and ₹8,000 reward. Recognition of Prior Learning (RPL) for existing skills.",
        "eligibility_rules_json": _rules(min_age=15, max_age=45),
        "required_documents_json": _docs("Aadhaar Card", "10th or 12th marksheet (for reference)", "Bank account passbook"),
        "application_url": "https://pmkvyofficial.org",
        "deadline": "2026-03-31",
        "source_name": "PMKVY Official",
        "source_url": "https://pmkvyofficial.org",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Skill India Centre / Training Partner Centre",
        "office_contact": "1800-123-9626",
    },
    {
        "name": "Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)",
        "name_hi": "दीन दयाल उपाध्याय ग्रामीण कौशल्या योजना",
        "category": "skill",
        "state_or_all_india": "ALL_INDIA",
        "description": "Placement-linked skill training for rural poor youth. Free residential training, food, accommodation, placement with at least ₹6,000/month salary. Targets rural BPL youth aged 15–35.",
        "eligibility_rules_json": _rules(min_age=15, max_age=35, max_income=100000),
        "required_documents_json": _docs("Aadhaar Card", "BPL certificate", "Age proof (birth certificate / school certificate)"),
        "application_url": "https://ddugky.gov.in",
        "deadline": None,
        "source_name": "DDU-GKY Portal",
        "source_url": "https://ddugky.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "State Rural Livelihoods Mission",
        "office_contact": "011-23383312",
    },
    {
        "name": "MGNREGA — Mahatma Gandhi National Rural Employment Guarantee Act",
        "name_hi": "मनरेगा",
        "category": "employment",
        "state_or_all_india": "ALL_INDIA",
        "description": "Guarantees 100 days of unskilled manual work per year to rural households. Wage rate: state-specific (₹200–₹380/day). Employment within 15 days of demand, else unemployment allowance. 33% reservation for women.",
        "eligibility_rules_json": _rules(min_age=18),
        "required_documents_json": _docs("Aadhaar Card", "Job card (issued by Gram Panchayat)", "Bank / post office account"),
        "application_url": "https://nrega.nic.in",
        "deadline": None,
        "source_name": "MGNREGA Portal",
        "source_url": "https://nrega.nic.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Gram Panchayat Office",
        "office_contact": "1800-11-0707",
    },
    {
        "name": "eShram — Unorganised Workers Registration",
        "name_hi": "ई-श्रम",
        "category": "employment",
        "state_or_all_india": "ALL_INDIA",
        "description": "National database of unorganised workers. Register to get eShram card with ₹2 lakh accident insurance under PMSBY. Links to other social security schemes. Covers migrant workers, gig workers, platform workers, construction workers.",
        "eligibility_rules_json": _rules(min_age=16, max_age=59),
        "required_documents_json": _docs("Aadhaar Card", "Mobile number linked to Aadhaar", "Bank account"),
        "application_url": "https://eshram.gov.in",
        "deadline": None,
        "source_name": "eShram Portal",
        "source_url": "https://eshram.gov.in",
        "last_verified_date": "2025-06-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "CSC or self-registration at eshram.gov.in",
        "office_contact": "14434",
    },

    # ── MSME / BUSINESS ──────────────────────────────────────────────────────
    {
        "name": "PM MUDRA Yojana (PMMY)",
        "name_hi": "प्रधानमंत्री मुद्रा योजना",
        "category": "msme",
        "state_or_all_india": "ALL_INDIA",
        "description": "Collateral-free loans to non-corporate, non-farm small/micro enterprises. Shishu: up to ₹50,000; Kishore: ₹50,001–₹5 lakh; Tarun: ₹5 lakh–₹10 lakh. No processing fee for Shishu. Tarun Plus: up to ₹20 lakh for Tarun graduates.",
        "eligibility_rules_json": _rules(occupation=["self_employed", "business"]),
        "required_documents_json": _docs("Aadhaar Card", "PAN Card", "Business plan / proof", "Bank statements (6 months)", "GST registration (if applicable)"),
        "application_url": "https://www.mudra.org.in",
        "deadline": None,
        "source_name": "MUDRA Official Portal",
        "source_url": "https://www.mudra.org.in",
        "last_verified_date": "2025-06-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Any bank, MFI, or NBFC",
        "office_contact": "1800-180-1111",
    },
    {
        "name": "PM SVANidhi — Street Vendor's AtmaNirbhar Nidhi",
        "name_hi": "पीएम स्वनिधि",
        "category": "msme",
        "state_or_all_india": "ALL_INDIA",
        "description": "Working capital loans for street vendors. Initial loan: ₹10,000; on repayment: ₹20,000, then ₹50,000. 7% interest subsidy. Digital transaction incentive: cashback up to ₹1,200/year.",
        "eligibility_rules_json": _rules(occupation=["street_vendor", "self_employed"]),
        "required_documents_json": _docs("Aadhaar Card", "Vending certificate or LoR from ULB", "Bank account"),
        "application_url": "https://pmsvanidhi.mohua.gov.in",
        "deadline": "2026-03-31",
        "source_name": "PM SVANidhi Portal",
        "source_url": "https://pmsvanidhi.mohua.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Urban Local Body (Municipal Corporation/Council)",
        "office_contact": "1800-11-1979",
    },
    {
        "name": "Stand-Up India Scheme",
        "name_hi": "स्टैंड-अप इंडिया",
        "category": "msme",
        "state_or_all_india": "ALL_INDIA",
        "description": "Bank loans between ₹10 lakh and ₹1 crore to at least one SC/ST borrower and one woman borrower per bank branch for greenfield enterprises. Covers manufacturing, services, and trading sectors.",
        "eligibility_rules_json": _rules(min_age=18, category=["sc", "st"]),
        "required_documents_json": _docs("Aadhaar Card", "PAN Card", "Caste certificate (SC/ST)", "Business plan", "Income tax returns"),
        "application_url": "https://www.standupmitra.in",
        "deadline": None,
        "source_name": "Stand-Up Mitra Portal",
        "source_url": "https://www.standupmitra.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Lead bank of district or SIDBI",
        "office_contact": "1800-180-1111",
    },
    {
        "name": "Startup India — DPIIT Recognition",
        "name_hi": "स्टार्टअप इंडिया",
        "category": "startup",
        "state_or_all_india": "ALL_INDIA",
        "description": "Recognition and support for startups. Benefits include 3-year income tax exemption, self-certification compliance, fast-track patent applications with 80% rebate, and government tender exemption from prior experience criteria.",
        "eligibility_rules_json": _rules(occupation="business", min_age=21),
        "required_documents_json": _docs("Certificate of Incorporation", "PAN Card", "Business plan / pitch deck", "Director's Aadhaar", "GST registration"),
        "application_url": "https://www.startupindia.gov.in",
        "deadline": None,
        "source_name": "Startup India Portal",
        "source_url": "https://www.startupindia.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "DPIIT, Ministry of Commerce, New Delhi",
        "office_contact": "011-23062261",
    },
    {
        "name": "Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)",
        "name_hi": "सीजीटीएमएसई",
        "category": "msme",
        "state_or_all_india": "ALL_INDIA",
        "description": "Provides credit guarantee for collateral-free loans to MSMEs. Covers up to 85% of credit facility up to ₹2 crore. Enables MSMEs to get loans without pledging assets.",
        "eligibility_rules_json": _rules(occupation=["business", "self_employed"]),
        "required_documents_json": _docs("Business registration", "GST registration", "Udyam Registration", "Bank statements", "ITR of last 2 years"),
        "application_url": "https://www.cgtmse.in",
        "deadline": None,
        "source_name": "CGTMSE Portal",
        "source_url": "https://www.cgtmse.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "SIDBI / any scheduled commercial bank",
        "office_contact": "022-67534100",
    },

    # ── SCHOLARSHIP / EDUCATION ───────────────────────────────────────────────
    {
        "name": "Pre-Matric Scholarship for SC/ST Students",
        "name_hi": "मैट्रिक पूर्व छात्रवृत्ति",
        "category": "scholarship",
        "state_or_all_india": "ALL_INDIA",
        "description": "Scholarship for SC/ST students studying in classes 9–10. Day scholars: ₹150–₹750/month + books. Hostellers: ₹350–₹1,000/month. Covers all government and government-aided schools.",
        "eligibility_rules_json": _rules(category=["sc", "st"], occupation="student", max_income=250000),
        "required_documents_json": _docs("Aadhaar Card", "Caste certificate", "Previous year marksheet", "Income certificate", "Bank passbook"),
        "application_url": "https://scholarships.gov.in",
        "deadline": "2025-10-31",
        "source_name": "NSP — Pre-Matric Scholarship",
        "source_url": "https://scholarships.gov.in",
        "last_verified_date": "2025-06-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Social Welfare Department, District Office",
        "office_contact": "0120-6619540",
    },
    {
        "name": "PM Scholarship for CAPF & AR Personnel",
        "name_hi": "केंद्रीय सशस्त्र पुलिस बलों के लिए पीएम छात्रवृत्ति",
        "category": "scholarship",
        "state_or_all_india": "ALL_INDIA",
        "description": "Scholarship for dependents of CAPFs, AR, and state police personnel killed in action or disabled. ₹3,000/month for boys, ₹3,500/month for girls. For professional degree courses.",
        "eligibility_rules_json": _rules(occupation="student", min_age=18),
        "required_documents_json": _docs("Aadhaar Card", "Bond / death certificate of parent (CAPF)", "Marksheet", "College admission letter"),
        "application_url": "https://ksb.gov.in",
        "deadline": "2025-11-30",
        "source_name": "KSB Portal",
        "source_url": "https://ksb.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Kendriya Sainik Board, New Delhi",
        "office_contact": "011-26173215",
    },
    {
        "name": "Ishan Uday — North East Region Scholarship",
        "name_hi": "ईशान उदय — पूर्वोत्तर क्षेत्र छात्रवृत्ति",
        "category": "scholarship",
        "state_or_all_india": "ALL_INDIA",
        "description": "Special scholarship for students from North East states. ₹5,400–₹7,800/month for UG and PG students. For students with family income up to ₹4.5 lakh.",
        "eligibility_rules_json": _rules(occupation="student", max_income=450000),
        "required_documents_json": _docs("Aadhaar Card", "Domicile certificate (NE state)", "Income certificate", "Marksheet", "College certificate"),
        "application_url": "https://scholarships.gov.in",
        "deadline": "2025-11-30",
        "source_name": "NSP — Ishan Uday",
        "source_url": "https://scholarships.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "University Grants Commission (UGC), New Delhi",
        "office_contact": "011-23604446",
    },

    # ── SENIOR CITIZEN ────────────────────────────────────────────────────────
    {
        "name": "Indira Gandhi National Old Age Pension Scheme (IGNOAPS)",
        "name_hi": "इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन योजना",
        "category": "senior_citizen",
        "state_or_all_india": "ALL_INDIA",
        "description": "Monthly pension to BPL elderly. ₹200/month for 60–79 years, ₹500/month for 80+ years from Central Government. States add matching or higher amounts. Disbursed directly to bank account.",
        "eligibility_rules_json": _rules(min_age=60, max_income=100000),
        "required_documents_json": _docs("Aadhaar Card", "Age proof (birth certificate / school certificate)", "BPL card", "Bank passbook"),
        "application_url": "https://nsap.nic.in",
        "deadline": None,
        "source_name": "NSAP Portal",
        "source_url": "https://nsap.nic.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Gram Panchayat / Ward Office",
        "office_contact": "011-23386444",
    },
    {
        "name": "Senior Citizen Savings Scheme (SCSS)",
        "name_hi": "वरिष्ठ नागरिक बचत योजना",
        "category": "senior_citizen",
        "state_or_all_india": "ALL_INDIA",
        "description": "5-year deposits for senior citizens with quarterly interest payout. Current rate: 8.2% p.a. Maximum deposit: ₹30 lakh. Tax benefit under 80C. Premature withdrawal allowed after 1 year.",
        "eligibility_rules_json": _rules(min_age=60),
        "required_documents_json": _docs("Aadhaar Card", "PAN Card", "Age proof", "Passport-size photograph"),
        "application_url": "https://www.nsiindia.gov.in",
        "deadline": None,
        "source_name": "NSI India — SCSS",
        "source_url": "https://www.nsiindia.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Any post office or authorised bank branch",
        "office_contact": "1800-11-2011",
    },

    # ── DISABILITY ────────────────────────────────────────────────────────────
    {
        "name": "Assistance to Disabled Persons for Purchase/Fitting of Aids (ADIP)",
        "name_hi": "विकलांग व्यक्तियों को सहायता",
        "category": "disability",
        "state_or_all_india": "ALL_INDIA",
        "description": "Free assistive devices for persons with disabilities: hearing aids, wheelchairs, tricycles, crutches, prosthetics. Income limit: ₹20,000/month. Quarterly camps organised at district level.",
        "eligibility_rules_json": _rules(max_income=240000),
        "required_documents_json": _docs("Aadhaar Card", "Disability certificate (40%+)", "Income certificate", "Physician certificate"),
        "application_url": "https://disabilityaffairs.gov.in",
        "deadline": None,
        "source_name": "DEPwD — ADIP Scheme",
        "source_url": "https://disabilityaffairs.gov.in",
        "last_verified_date": "2025-03-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Social Welfare / Disability Office",
        "office_contact": "011-23381747",
    },
    {
        "name": "NHFDC — National Handicapped Finance & Development Corporation Loans",
        "name_hi": "एनएचएफडीसी ऋण",
        "category": "disability",
        "state_or_all_india": "ALL_INDIA",
        "description": "Concessional loans for self-employment to persons with disabilities. General: 6% p.a.; women/SC/ST: 5% p.a. Loans up to ₹30 lakh for income generation activities.",
        "eligibility_rules_json": _rules(min_age=18, max_income=600000),
        "required_documents_json": _docs("Aadhaar Card", "Disability certificate (40%+)", "Business plan", "Income proof"),
        "application_url": "https://nhfdc.nic.in",
        "deadline": None,
        "source_name": "NHFDC Portal",
        "source_url": "https://nhfdc.nic.in",
        "last_verified_date": "2025-03-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "State Channelizing Agency",
        "office_contact": "0120-2403872",
    },

    # ── DIGITAL / TECHNOLOGY ─────────────────────────────────────────────────
    {
        "name": "Digital India — BharatNet",
        "name_hi": "डिजिटल इंडिया — भारतनेट",
        "category": "digital",
        "state_or_all_india": "ALL_INDIA",
        "description": "Optical fibre connectivity to all 2.5 lakh gram panchayats. Provides free/subsidised broadband to rural areas. Wi-Fi hotspots at gram panchayats. 100 Mbps bandwidth at affordable rates.",
        "eligibility_rules_json": _rules(min_age=18),
        "required_documents_json": _docs("Aadhaar Card", "Residence proof"),
        "application_url": "https://bbnl.nic.in",
        "deadline": None,
        "source_name": "BBNL — BharatNet",
        "source_url": "https://bbnl.nic.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Gram Panchayat / CSC",
        "office_contact": "1800-180-1515",
    },
    {
        "name": "PM GatiShakti — National Master Plan",
        "name_hi": "पीएम गति शक्ति",
        "category": "infrastructure",
        "state_or_all_india": "ALL_INDIA",
        "description": "Multi-modal connectivity infrastructure masterplan integrating 16 ministries. Benefits businesses and citizens through faster approvals for industrial areas, logistics, roads, railways. Single-window clearance portal.",
        "eligibility_rules_json": _rules(occupation="business"),
        "required_documents_json": _docs("Business registration", "Project plan"),
        "application_url": "https://pmgatishakti.gov.in",
        "deadline": None,
        "source_name": "PM GatiShakti Portal",
        "source_url": "https://pmgatishakti.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Ministry of Commerce, New Delhi",
        "office_contact": "1800-572-7879",
    },

    # ── TRIBAL ────────────────────────────────────────────────────────────────
    {
        "name": "PM-JANMAN — Particularly Vulnerable Tribal Groups Development Mission",
        "name_hi": "पीएम जनमन",
        "category": "tribal",
        "state_or_all_india": "ALL_INDIA",
        "description": "Mission to improve the socio-economic conditions of 75 Particularly Vulnerable Tribal Groups (PVTGs). Provides pucca housing, safe drinking water, electricity, mobile health, anganwadi, and connectivity.",
        "eligibility_rules_json": _rules(category="st"),
        "required_documents_json": _docs("Aadhaar Card", "ST certificate", "PVTG community certificate"),
        "application_url": "https://tribal.gov.in",
        "deadline": "2026-03-31",
        "source_name": "Ministry of Tribal Affairs",
        "source_url": "https://tribal.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Tribal Welfare Office",
        "office_contact": "011-23793746",
    },
    {
        "name": "Eklavya Model Residential Schools (EMRS)",
        "name_hi": "एकलव्य मॉडल आवासीय विद्यालय",
        "category": "tribal",
        "state_or_all_india": "ALL_INDIA",
        "description": "Residential schools for ST students in remote tribal areas providing quality education equivalent to Navodaya Vidyalayas. Free education, boarding, food, and extracurricular facilities. Covers classes 6–12.",
        "eligibility_rules_json": _rules(category="st", occupation="student", max_age=18),
        "required_documents_json": _docs("Aadhaar Card", "ST certificate", "School leaving certificate", "Entrance test hall ticket"),
        "application_url": "https://emrs.tribal.gov.in",
        "deadline": "2025-05-31",
        "source_name": "EMRS Portal",
        "source_url": "https://emrs.tribal.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Tribal Welfare Office",
        "office_contact": "011-23793746",
    },

    # ── STATE SCHEMES — BIHAR ─────────────────────────────────────────────────
    {
        "name": "Mukhyamantri Kanya Utthan Yojana (Bihar)",
        "name_hi": "मुख्यमंत्री कन्या उत्थान योजना",
        "category": "women",
        "state_or_all_india": "BIHAR",
        "description": "Incentive to Bihar girl students for education. ₹25,000 for UG graduation, ₹50,000 for post-graduation. ₹5,000 at birth. Dress and sanitary pad allowance from class 1–12.",
        "eligibility_rules_json": _rules(gender="female", occupation="student", max_income=150000),
        "required_documents_json": _docs("Aadhaar Card", "Income certificate", "Degree certificate", "Bank passbook", "Caste certificate"),
        "application_url": "https://medhasoft.bih.nic.in",
        "deadline": "2025-12-31",
        "source_name": "Bihar Govt — MedhaSOFT",
        "source_url": "https://medhasoft.bih.nic.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Education Office, Bihar",
        "office_contact": "0612-2215448",
    },
    {
        "name": "Bihar Student Credit Card Scheme",
        "name_hi": "बिहार स्टूडेंट क्रेडिट कार्ड योजना",
        "category": "scholarship",
        "state_or_all_india": "BIHAR",
        "description": "Education loan up to ₹4 lakh at 4% interest (1% for women/SC/ST/PH) for students who have passed 12th from Bihar. Covers 42+ recognized courses including Engineering, Medical, Management, Law.",
        "eligibility_rules_json": _rules(occupation="student", max_age=25, max_income=450000),
        "required_documents_json": _docs("Aadhaar Card", "12th certificate (Bihar board)", "Income certificate", "Bank passbook", "Bonafide certificate"),
        "application_url": "https://7nishchay-yuvaupmission.bihar.gov.in",
        "deadline": None,
        "source_name": "Bihar BSCC Portal",
        "source_url": "https://7nishchay-yuvaupmission.bihar.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Registration and Counselling Centre, Bihar",
        "office_contact": "1800-3456-444",
    },
    {
        "name": "Har Ghar Bijli — Bihar",
        "name_hi": "हर घर बिजली — बिहार",
        "category": "energy",
        "state_or_all_india": "BIHAR",
        "description": "Bihar government scheme to provide electricity connection to every household. Free connection for BPL households. Meter and wiring cost covered. Part of state's 7 Nishchay programme.",
        "eligibility_rules_json": _rules(max_income=100000),
        "required_documents_json": _docs("Aadhaar Card", "BPL card", "Residence proof"),
        "application_url": "https://hargharbijli.bsphcl.co.in",
        "deadline": None,
        "source_name": "BSPHCL — Har Ghar Bijli",
        "source_url": "https://bsphcl.co.in",
        "last_verified_date": "2025-03-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "BSPHCL District Office",
        "office_contact": "1912",
    },

    # ── STATE SCHEMES — UTTAR PRADESH ─────────────────────────────────────────
    {
        "name": "Kanya Sumangala Yojana (Uttar Pradesh)",
        "name_hi": "कन्या सुमंगला योजना",
        "category": "women",
        "state_or_all_india": "UTTAR_PRADESH",
        "description": "Financial assistance for girl child in UP in 6 stages: ₹2,000 at birth, ₹1,000 at vaccination, ₹2,000 at class 1 admission, ₹2,000 at class 6, ₹3,000 at class 9, ₹5,000 at graduation. Total: ₹15,000.",
        "eligibility_rules_json": _rules(gender="female", max_income=300000),
        "required_documents_json": _docs("Aadhaar Card", "Birth certificate", "Income certificate", "Domicile certificate (UP)", "Bank passbook"),
        "application_url": "https://mksy.up.gov.in",
        "deadline": None,
        "source_name": "MKSY UP Portal",
        "source_url": "https://mksy.up.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Block / District Probation Officer, UP",
        "office_contact": "0522-2209090",
    },
    {
        "name": "UP Mukhyamantri Yuva Swarozgar Yojana",
        "name_hi": "मुख्यमंत्री युवा स्वरोजगार योजना",
        "category": "msme",
        "state_or_all_india": "UTTAR_PRADESH",
        "description": "Subsidised loans for self-employment to unemployed educated youth in UP. Loan up to ₹25 lakh for industry sector, ₹10 lakh for service sector. 25% margin money subsidy. Priority to SC/ST, women, disabled.",
        "eligibility_rules_json": _rules(min_age=18, max_age=40, max_income=300000),
        "required_documents_json": _docs("Aadhaar Card", "Educational qualification certificate", "Residence certificate (UP)", "Bank passbook", "Project report"),
        "application_url": "https://diupmsme.upsdc.gov.in",
        "deadline": None,
        "source_name": "UP MSME Portal",
        "source_url": "https://diupmsme.upsdc.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Industries Centre, UP",
        "office_contact": "0522-2237582",
    },
    {
        "name": "Samajwadi Pension Yojana (UP)",
        "name_hi": "समाजवादी पेंशन योजना",
        "category": "senior_citizen",
        "state_or_all_india": "UTTAR_PRADESH",
        "description": "Monthly pension of ₹500–₹1,000 for old age, widow, and disabled persons in UP below poverty line. Direct bank transfer.",
        "eligibility_rules_json": _rules(min_age=60, max_income=100000),
        "required_documents_json": _docs("Aadhaar Card", "Age proof", "Income certificate", "Bank passbook"),
        "application_url": "https://sspy-up.gov.in",
        "deadline": None,
        "source_name": "SSPY — UP Pension Portal",
        "source_url": "https://sspy-up.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Block / Tehsil Office, UP",
        "office_contact": "1800-419-0001",
    },

    # ── STATE SCHEMES — MAHARASHTRA ───────────────────────────────────────────
    {
        "name": "Mahatma Jyotirao Phule Jan Arogya Yojana (Maharashtra)",
        "name_hi": "महात्मा ज्योतिराव फुले जन आरोग्य योजना",
        "category": "health",
        "state_or_all_india": "MAHARASHTRA",
        "description": "Health insurance up to ₹5 lakh per year for BPL and APL families in Maharashtra. Cashless treatment at 500+ hospitals. Covers 996 procedures including cardiac, neuro, ortho surgeries and cancer treatment.",
        "eligibility_rules_json": _rules(max_income=100000),
        "required_documents_json": _docs("Aadhaar Card", "Ration card (Yellow/Orange/White)", "Income certificate", "Domicile certificate (Maharashtra)"),
        "application_url": "https://jeevandayee.gov.in",
        "deadline": None,
        "source_name": "Jeevandayee Portal",
        "source_url": "https://jeevandayee.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Civil Hospital / Network Hospital",
        "office_contact": "1800-233-2200",
    },
    {
        "name": "Namo Shetkari Maha Samman Nidhi (Maharashtra)",
        "name_hi": "नमो शेतकरी महासम्मान निधि",
        "category": "farmer",
        "state_or_all_india": "MAHARASHTRA",
        "description": "Maharashtra-specific income support to farmers in addition to PM-KISAN. ₹6,000 per year in 3 instalments. Combined with PM-KISAN gives ₹12,000/year total.",
        "eligibility_rules_json": _rules(occupation="farmer", max_income=200000),
        "required_documents_json": _docs("Aadhaar Card", "7/12 land record extract", "Bank passbook"),
        "application_url": "https://agri.maharashtra.gov.in",
        "deadline": None,
        "source_name": "Maharashtra Agriculture",
        "source_url": "https://agri.maharashtra.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Tehsil Agriculture Officer, Maharashtra",
        "office_contact": "1800-233-4000",
    },
    {
        "name": "CM Ladki Bahin Yojana (Maharashtra)",
        "name_hi": "लाडकी बहीण योजना",
        "category": "women",
        "state_or_all_india": "MAHARASHTRA",
        "description": "Monthly financial assistance of ₹1,500 to women aged 21–65 years in Maharashtra. Annual benefit: ₹18,000. Aadhaar-linked direct bank transfer.",
        "eligibility_rules_json": _rules(gender="female", min_age=21, max_age=65, max_income=250000),
        "required_documents_json": _docs("Aadhaar Card", "Bank passbook", "Income certificate", "Maharashtra domicile proof"),
        "application_url": "https://ladakibahin.maharashtra.gov.in",
        "deadline": None,
        "source_name": "Maharashtra WCD",
        "source_url": "https://ladakibahin.maharashtra.gov.in",
        "last_verified_date": "2025-06-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Anganwadi Centre / Gram Sevak Office",
        "office_contact": "1800-213-0125",
    },

    # ── STATE SCHEMES — KARNATAKA ─────────────────────────────────────────────
    {
        "name": "Shakti Scheme — Free Bus Travel for Women (Karnataka)",
        "name_hi": "शक्ति योजना — महिलाओं के लिए मुफ्त बस यात्रा",
        "category": "women",
        "state_or_all_india": "KARNATAKA",
        "description": "Free travel for women in Karnataka State Road Transport Corporation (KSRTC) and BMTC buses. Valid across all routes in Karnataka. No age limit. Requires women's Aadhaar.",
        "eligibility_rules_json": _rules(gender="female"),
        "required_documents_json": _docs("Aadhaar Card (or Shakti Smart Card)"),
        "application_url": "https://ksrtc.in",
        "deadline": None,
        "source_name": "KSRTC Karnataka",
        "source_url": "https://ksrtc.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "KSRTC Bus Stand / BMTC Office",
        "office_contact": "1800-4257-947",
    },
    {
        "name": "Yuva Nidhi Scheme (Karnataka)",
        "name_hi": "युवा निधि योजना",
        "category": "employment",
        "state_or_all_india": "KARNATAKA",
        "description": "Unemployment allowance for educated unemployed youth in Karnataka. Degree graduates: ₹3,000/month; Diploma holders: ₹1,500/month. For 2 years or until employed.",
        "eligibility_rules_json": _rules(min_age=18, max_age=25, max_income=300000),
        "required_documents_json": _docs("Aadhaar Card", "Degree/Diploma certificate", "Domicile certificate (Karnataka)", "Bank passbook", "Employment Exchange registration"),
        "application_url": "https://sevasindhu.karnataka.gov.in",
        "deadline": None,
        "source_name": "Seva Sindhu Karnataka",
        "source_url": "https://sevasindhu.karnataka.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Seva Sindhu Centre / District Employment Office",
        "office_contact": "080-22346563",
    },

    # ── STATE SCHEMES — GUJARAT ───────────────────────────────────────────────
    {
        "name": "Mukhyamantri Mahila Utkarsh Yojana (Gujarat)",
        "name_hi": "मुख्यमंत्री महिला उत्कर्ष योजना",
        "category": "women",
        "state_or_all_india": "GUJARAT",
        "description": "Interest-free loans up to ₹1 lakh to women SHG members in Gujarat through Urban Credit Societies. No collateral, no guarantor required.",
        "eligibility_rules_json": _rules(gender="female"),
        "required_documents_json": _docs("Aadhaar Card", "SHG membership proof", "Bank passbook"),
        "application_url": "https://mmuy.gujarat.gov.in",
        "deadline": None,
        "source_name": "Gujarat WCD Department",
        "source_url": "https://wcd.gujarat.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Social Defence Office, Gujarat",
        "office_contact": "079-23253891",
    },
    {
        "name": "Kisan Suryoday Yojana (Gujarat)",
        "name_hi": "किसान सूर्योदय योजना",
        "category": "farmer",
        "state_or_all_india": "GUJARAT",
        "description": "3-phase power supply to agricultural connections from 5 AM to 9 PM. Ensures farmers get daytime electricity for irrigation. Eliminating need for diesel pumps.",
        "eligibility_rules_json": _rules(occupation="farmer"),
        "required_documents_json": _docs("Aadhaar Card", "Land records", "Existing electricity connection number"),
        "application_url": "https://agri.gujarat.gov.in",
        "deadline": None,
        "source_name": "Gujarat Agriculture",
        "source_url": "https://agri.gujarat.gov.in",
        "last_verified_date": "2025-03-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Agriculture Office, Gujarat",
        "office_contact": "1800-233-1015",
    },

    # ── STATE SCHEMES — RAJASTHAN ─────────────────────────────────────────────
    {
        "name": "Chiranjeevi Swasthya Bima Yojana (Rajasthan)",
        "name_hi": "मुख्यमंत्री चिरंजीवी स्वास्थ्य बीमा योजना",
        "category": "health",
        "state_or_all_india": "RAJASTHAN",
        "description": "Health insurance up to ₹25 lakh per family per year in Rajasthan. Cashless treatment at 1,000+ hospitals. Covers OPD in addition to IPD. Priority diseases covered from first day.",
        "eligibility_rules_json": _rules(max_income=200000),
        "required_documents_json": _docs("Aadhaar Card", "Jan Aadhaar card", "Income certificate"),
        "application_url": "https://chiranjeevi.rajasthan.gov.in",
        "deadline": None,
        "source_name": "Rajasthan Chiranjeevi Yojana",
        "source_url": "https://chiranjeevi.rajasthan.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Health Office, Rajasthan",
        "office_contact": "1800-180-6127",
    },
    {
        "name": "Rajasthan Free Laptop Vitran Yojana",
        "name_hi": "राजस्थान फ्री लैपटॉप वितरण योजना",
        "category": "scholarship",
        "state_or_all_india": "RAJASTHAN",
        "description": "Free laptops to meritorious class 8, 10, 12 students in Rajasthan. Top scorers from each district. Also for JEE/NEET qualified students from Rajasthan.",
        "eligibility_rules_json": _rules(occupation="student", max_age=20, max_income=200000),
        "required_documents_json": _docs("Aadhaar Card", "Marksheet (class 8/10/12)", "Rajasthan domicile", "Bank passbook"),
        "application_url": "https://rajeduboard.rajasthan.gov.in",
        "deadline": "2025-10-31",
        "source_name": "Rajasthan Education Department",
        "source_url": "https://rajeduboard.rajasthan.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Education Office, Rajasthan",
        "office_contact": "1800-180-6127",
    },

    # ── STATE SCHEMES — TELANGANA ─────────────────────────────────────────────
    {
        "name": "Rythu Bandhu Scheme (Telangana)",
        "name_hi": "रायथु बंधु योजना",
        "category": "farmer",
        "state_or_all_india": "TELANGANA",
        "description": "₹10,000 per acre per year investment support to Telangana farmers. Paid in two installments: Kharif (₹5,000) and Rabi (₹5,000). No loan requirement. Direct bank credit.",
        "eligibility_rules_json": _rules(occupation="farmer"),
        "required_documents_json": _docs("Aadhaar Card", "Pahani (land records)", "Bank passbook"),
        "application_url": "https://rythubandhu.telangana.gov.in",
        "deadline": None,
        "source_name": "Telangana Agriculture",
        "source_url": "https://rythubandhu.telangana.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Village Revenue Officer / Agriculture Extension Officer",
        "office_contact": "1800-425-0877",
    },
    {
        "name": "Kalyana Lakshmi / Shaadi Mubarak (Telangana)",
        "name_hi": "कल्याण लक्ष्मी / शादी मुबारक",
        "category": "women",
        "state_or_all_india": "TELANGANA",
        "description": "Marriage assistance to SC/ST/OBC/EBC girls and Muslim girls in Telangana. ₹1,00,116 assistance per marriage. Paid directly to girl's account.",
        "eligibility_rules_json": _rules(gender="female", max_income=200000, category=["sc", "st", "obc"]),
        "required_documents_json": _docs("Aadhaar Card", "Caste certificate", "Income certificate", "Marriage certificate", "Bank passbook"),
        "application_url": "https://telanganaepass.cgg.gov.in",
        "deadline": None,
        "source_name": "Telangana ePass",
        "source_url": "https://telanganaepass.cgg.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Mandal Revenue Office, Telangana",
        "office_contact": "040-23393939",
    },

    # ── STATE SCHEMES — TAMIL NADU ────────────────────────────────────────────
    {
        "name": "Kalaignar Magalir Urimai Thogai Thittam (Tamil Nadu)",
        "name_hi": "कलैग्नर महिला अधिकार योजना",
        "category": "women",
        "state_or_all_india": "TAMIL_NADU",
        "description": "Monthly financial assistance of ₹1,000 to women head of households in Tamil Nadu. Target: 1 crore families. Direct bank transfer every month.",
        "eligibility_rules_json": _rules(gender="female", max_income=250000),
        "required_documents_json": _docs("Aadhaar Card", "Ration card", "Bank passbook", "TN domicile proof"),
        "application_url": "https://muut.tn.gov.in",
        "deadline": None,
        "source_name": "TN Social Welfare",
        "source_url": "https://tnswdept.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Block Social Welfare Office, Tamil Nadu",
        "office_contact": "044-28511111",
    },

    # ── STATE SCHEMES — ODISHA ────────────────────────────────────────────────
    {
        "name": "KALIA Scheme (Odisha) — Krushak Assistance for Livelihood and Income Augmentation",
        "name_hi": "कालिया योजना — ओडिशा",
        "category": "farmer",
        "state_or_all_india": "ODISHA",
        "description": "₹25,000 per family over 5 years for small and marginal farmers. ₹5,000/season for crop production support. Free life insurance ₹2 lakh. Free personal accident insurance ₹2 lakh.",
        "eligibility_rules_json": _rules(occupation="farmer"),
        "required_documents_json": _docs("Aadhaar Card", "Land records (RoR)", "Bank passbook"),
        "application_url": "https://kalia.odisha.gov.in",
        "deadline": None,
        "source_name": "KALIA Portal",
        "source_url": "https://kalia.odisha.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Block Agriculture Office, Odisha",
        "office_contact": "1800-345-6770",
    },
    {
        "name": "Subhadra Yojana (Odisha)",
        "name_hi": "सुभद्रा योजना — ओडिशा",
        "category": "women",
        "state_or_all_india": "ODISHA",
        "description": "One-time assistance of ₹50,000 to women aged 21–60 years in Odisha over 2 years (₹25,000/year as voucher). For purchasing household items and meeting personal needs.",
        "eligibility_rules_json": _rules(gender="female", min_age=21, max_age=60, max_income=250000),
        "required_documents_json": _docs("Aadhaar Card", "Residence certificate (Odisha)", "Bank passbook"),
        "application_url": "https://subhadra.odisha.gov.in",
        "deadline": "2026-03-31",
        "source_name": "Subhadra Portal",
        "source_url": "https://subhadra.odisha.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Gram Panchayat / Urban Local Body, Odisha",
        "office_contact": "1800-345-6770",
    },

    # ── STATE SCHEMES — WEST BENGAL ───────────────────────────────────────────
    {
        "name": "Lakshmir Bhandar (West Bengal)",
        "name_hi": "लक्ष्मीर भंडार",
        "category": "women",
        "state_or_all_india": "WEST_BENGAL",
        "description": "Monthly allowance for women head of family in West Bengal. General category: ₹1,000/month; SC/ST: ₹1,200/month. Direct bank transfer.",
        "eligibility_rules_json": _rules(gender="female", min_age=25, max_age=60, max_income=250000),
        "required_documents_json": _docs("Aadhaar Card", "Swasthya Sathi card / ration card", "Bank passbook", "WB residence proof"),
        "application_url": "https://socialsecurity.wb.gov.in",
        "deadline": None,
        "source_name": "WB Social Security",
        "source_url": "https://socialsecurity.wb.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Duare Sarkar / Block Development Office",
        "office_contact": "1800-345-5555",
    },
    {
        "name": "Swasthya Sathi (West Bengal)",
        "name_hi": "स्वास्थ्य साथी",
        "category": "health",
        "state_or_all_india": "WEST_BENGAL",
        "description": "Cashless health coverage of ₹5 lakh per family per year. Covers all state government and private hospitals in WB. Smart card-based. Covers over 10 crore WB residents.",
        "eligibility_rules_json": _rules(max_income=200000),
        "required_documents_json": _docs("Aadhaar Card", "Ration card", "Swasthya Sathi card (existing holders)"),
        "application_url": "https://swasthyasathi.gov.in",
        "deadline": None,
        "source_name": "Swasthya Sathi Portal",
        "source_url": "https://swasthyasathi.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Duare Sarkar / District Health Office",
        "office_contact": "1800-345-5555",
    },

    # ── INSURANCE ────────────────────────────────────────────────────────────
    {
        "name": "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
        "name_hi": "प्रधानमंत्री जीवन ज्योति बीमा योजना",
        "category": "financial_inclusion",
        "state_or_all_india": "ALL_INDIA",
        "description": "Renewable life insurance cover of ₹2 lakh at just ₹436/year. Auto-debit from bank account. Covers death from any cause. No medical examination required.",
        "eligibility_rules_json": _rules(min_age=18, max_age=50),
        "required_documents_json": _docs("Aadhaar-linked bank account", "Aadhaar Card"),
        "application_url": "https://jansuraksha.gov.in",
        "deadline": "2025-05-31",
        "source_name": "Jan Suraksha",
        "source_url": "https://jansuraksha.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Nearest bank branch",
        "office_contact": "1800-180-1111",
    },
    {
        "name": "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
        "name_hi": "प्रधानमंत्री सुरक्षा बीमा योजना",
        "category": "financial_inclusion",
        "state_or_all_india": "ALL_INDIA",
        "description": "Accidental insurance at just ₹20/year. ₹2 lakh for accidental death/permanent disability, ₹1 lakh for partial permanent disability. Auto-renewal. Covers eShram cardholders automatically.",
        "eligibility_rules_json": _rules(min_age=18, max_age=70),
        "required_documents_json": _docs("Aadhaar-linked bank account", "Aadhaar Card"),
        "application_url": "https://jansuraksha.gov.in",
        "deadline": "2025-05-31",
        "source_name": "Jan Suraksha",
        "source_url": "https://jansuraksha.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Nearest bank branch or BC",
        "office_contact": "1800-180-1111",
    },

    # ── FOOD SECURITY ────────────────────────────────────────────────────────
    {
        "name": "Pradhan Mantri Garib Kalyan Anna Yojana (PMGKAY)",
        "name_hi": "प्रधानमंत्री गरीब कल्याण अन्न योजना",
        "category": "food_security",
        "state_or_all_india": "ALL_INDIA",
        "description": "Free food grain distribution to NFSA beneficiaries. 5 kg wheat/rice per person per month at no cost. Covers 81.35 crore people. Extended indefinitely under NFSA.",
        "eligibility_rules_json": _rules(max_income=100000),
        "required_documents_json": _docs("Ration card (NFSA)", "Aadhaar Card"),
        "application_url": "https://dfpd.gov.in",
        "deadline": None,
        "source_name": "DFPD — Food Grain Distribution",
        "source_url": "https://dfpd.gov.in",
        "last_verified_date": "2025-06-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Nearest PDS / Ration Shop",
        "office_contact": "1967",
    },
    {
        "name": "PM Poshan — Mid Day Meal Scheme",
        "name_hi": "पीएम पोषण",
        "category": "food_security",
        "state_or_all_india": "ALL_INDIA",
        "description": "Free cooked meal to all children in government and government-aided schools (Class 1–8). Improves attendance, retention, and nutrition. Covers 11.80 crore children daily.",
        "eligibility_rules_json": _rules(occupation="student", max_age=14),
        "required_documents_json": _docs("School enrollment proof"),
        "application_url": "https://pmposhan.education.gov.in",
        "deadline": None,
        "source_name": "PM Poshan Portal",
        "source_url": "https://pmposhan.education.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "School / District Education Office",
        "office_contact": "011-23385961",
    },

    # ── WATER / SANITATION ────────────────────────────────────────────────────
    {
        "name": "Jal Jeevan Mission — Har Ghar Jal",
        "name_hi": "जल जीवन मिशन — हर घर जल",
        "category": "infrastructure",
        "state_or_all_india": "ALL_INDIA",
        "description": "Provides safe and adequate drinking water to every rural household through individual tap connections by 2024. 19+ crore tap connections achieved. Free connection for BPL households.",
        "eligibility_rules_json": _rules(min_age=18),
        "required_documents_json": _docs("Aadhaar Card", "Land/house ownership proof", "Application to Gram Panchayat"),
        "application_url": "https://jaljeevanmission.gov.in",
        "deadline": "2026-03-31",
        "source_name": "Jal Jeevan Mission",
        "source_url": "https://jaljeevanmission.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Gram Panchayat / District Water & Sanitation Office",
        "office_contact": "1916",
    },
    {
        "name": "Swachh Bharat Mission — Gramin (SBM-G) 2.0",
        "name_hi": "स्वच्छ भारत मिशन — ग्रामीण",
        "category": "sanitation",
        "state_or_all_india": "ALL_INDIA",
        "description": "Incentive for construction of Individual Household Latrines (IHHLs). ₹12,000 incentive for BPL households. ODF+ and ODF++ certification with improved sanitation infrastructure.",
        "eligibility_rules_json": _rules(max_income=100000),
        "required_documents_json": _docs("Aadhaar Card", "BPL card", "Verification by Gram Panchayat"),
        "application_url": "https://sbm.gov.in",
        "deadline": "2026-03-31",
        "source_name": "SBM Portal",
        "source_url": "https://sbm.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Gram Panchayat / Block Development Office",
        "office_contact": "1969",
    },

    # ── SOCIAL PROTECTION ────────────────────────────────────────────────────
    {
        "name": "National Social Assistance Programme (NSAP) — Widow Pension",
        "name_hi": "राष्ट्रीय सामाजिक सहायता कार्यक्रम — विधवा पेंशन",
        "category": "women",
        "state_or_all_india": "ALL_INDIA",
        "description": "Monthly pension to BPL widows. IGNWPS: ₹300/month for 40–79 years, ₹500 for 80+. Most states add extra amounts. Direct bank transfer.",
        "eligibility_rules_json": _rules(gender="female", min_age=40, max_income=100000),
        "required_documents_json": _docs("Aadhaar Card", "Husband's death certificate", "BPL proof", "Age proof", "Bank passbook"),
        "application_url": "https://nsap.nic.in",
        "deadline": None,
        "source_name": "NSAP Portal",
        "source_url": "https://nsap.nic.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Gram Panchayat / Municipal Corporation",
        "office_contact": "011-23386444",
    },
    {
        "name": "PM Matru Vandana Yojana (PMMVY)",
        "name_hi": "प्रधानमंत्री मातृ वंदना योजना",
        "category": "women",
        "state_or_all_india": "ALL_INDIA",
        "description": "Maternity benefit of ₹5,000 in 3 installments for first child. Second child if girl: ₹6,000 in 2 installments. Compensates wage loss during pregnancy. Promotes institutional delivery.",
        "eligibility_rules_json": _rules(gender="female", min_age=19),
        "required_documents_json": _docs("Aadhaar Card", "MCP card (Mother and Child Protection)", "Bank passbook", "Pregnancy registration at health centre"),
        "application_url": "https://pmmvy.wcd.gov.in",
        "deadline": None,
        "source_name": "PMMVY Portal",
        "source_url": "https://pmmvy.wcd.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Anganwadi Centre / Health Sub-Centre",
        "office_contact": "1800-111-565",
    },

    # ── ENVIRONMENT / GREEN ──────────────────────────────────────────────────
    {
        "name": "PM Kusum Yojana — Solar Pump for Farmers",
        "name_hi": "पीएम कुसुम योजना",
        "category": "farmer",
        "state_or_all_india": "ALL_INDIA",
        "description": "60% subsidy on solar pump installation for farmers. Reduces diesel cost and provides water security. Farmers can also sell surplus solar power to grid for extra income. Covers 2 HP to 10 HP pumps.",
        "eligibility_rules_json": _rules(occupation="farmer"),
        "required_documents_json": _docs("Aadhaar Card", "Land records", "Bank passbook", "Existing pump details"),
        "application_url": "https://mnre.gov.in/solar/schemes/",
        "deadline": "2026-03-31",
        "source_name": "MNRE — PM Kusum",
        "source_url": "https://mnre.gov.in",
        "last_verified_date": "2025-05-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "DISCOM / State Nodal Agency for Renewable Energy",
        "office_contact": "011-24363333",
    },

    # ── TRANSPORT ────────────────────────────────────────────────────────────
    {
        "name": "PM E-Bus Sewa",
        "name_hi": "पीएम ई-बस सेवा",
        "category": "transport",
        "state_or_all_india": "ALL_INDIA",
        "description": "Deployment of 10,000 electric buses in 169 cities with 1.5–8 lakh population. Subsidised fares. Reduces pollution and provides affordable public transport.",
        "eligibility_rules_json": json.dumps({"logic": "AND", "rules": []}),
        "required_documents_json": json.dumps([]),
        "application_url": "https://pme-bus.in",
        "deadline": None,
        "source_name": "MoHUA — PM E-Bus Sewa",
        "source_url": "https://mohua.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Urban Local Body / SRTC",
        "office_contact": "011-23062691",
    },

    # ── FISHERIES ────────────────────────────────────────────────────────────
    {
        "name": "Pradhan Mantri Matsya Sampada Yojana (PMMSY)",
        "name_hi": "प्रधानमंत्री मत्स्य संपदा योजना",
        "category": "farmer",
        "state_or_all_india": "ALL_INDIA",
        "description": "₹20,050 crore scheme to bring Blue Revolution. Subsidies for aquaculture, deep sea fishing vessels, fish processing units. Covers fishermen, fish farmers, and workers. Insurance for fishing boats.",
        "eligibility_rules_json": _rules(occupation=["farmer", "fisherman"]),
        "required_documents_json": _docs("Aadhaar Card", "Fisherman registration", "Bank passbook", "Boat registration certificate"),
        "application_url": "https://pmmsy.dof.gov.in",
        "deadline": "2026-03-31",
        "source_name": "PMMSY Portal",
        "source_url": "https://pmmsy.dof.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Fisheries Officer",
        "office_contact": "011-23382655",
    },

    # ── TEXTILES / HANDICRAFTS ───────────────────────────────────────────────
    {
        "name": "Samarth — Scheme for Capacity Building in Textile Sector",
        "name_hi": "समर्थ",
        "category": "skill",
        "state_or_all_india": "ALL_INDIA",
        "description": "Free skill training for youth in textile, apparel, garments, and made-up sectors. Residential training with stipend. Placement within 70 days of training completion.",
        "eligibility_rules_json": _rules(min_age=18, max_age=35),
        "required_documents_json": _docs("Aadhaar Card", "Educational certificate", "Bank passbook"),
        "application_url": "https://samarth-textiles.gov.in",
        "deadline": "2026-03-31",
        "source_name": "Samarth Portal",
        "source_url": "https://samarth-textiles.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Industries Centre / Textile Commissioner",
        "office_contact": "011-23061500",
    },

    # ── RURAL DEVELOPMENT ────────────────────────────────────────────────────
    {
        "name": "Deen Dayal Antyodaya Yojana — National Rural Livelihoods Mission (DAY-NRLM)",
        "name_hi": "दीन दयाल अंत्योदय योजना — राष्ट्रीय ग्रामीण आजीविका मिशन",
        "category": "employment",
        "state_or_all_india": "ALL_INDIA",
        "description": "Organises poor rural women into Self Help Groups (SHGs) with revolving funds, Community Investment Funds, and bank credit access. Interest subvention at 7%. Training for income generation.",
        "eligibility_rules_json": _rules(gender="female", max_income=200000),
        "required_documents_json": _docs("Aadhaar Card", "Ration card", "Bank passbook"),
        "application_url": "https://aajeevika.gov.in",
        "deadline": None,
        "source_name": "NRLM — Aajeevika",
        "source_url": "https://aajeevika.gov.in",
        "last_verified_date": "2025-04-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "Block Rural Livelihood Mission / SHG facilitator",
        "office_contact": "011-23383312",
    },
    {
        "name": "Shyama Prasad Mukherji Rurban Mission (SPMRM)",
        "name_hi": "श्यामा प्रसाद मुखर्जी रर्बन मिशन",
        "category": "infrastructure",
        "state_or_all_india": "ALL_INDIA",
        "description": "Development of 300 rural clusters with urban amenities: roads, piped water, sewerage, streetlights, digital connectivity, schools, skill centres. Focus on rural growth centres.",
        "eligibility_rules_json": json.dumps({"logic": "AND", "rules": []}),
        "required_documents_json": json.dumps([{"name": "Residence proof in notified cluster", "mandatory": True}]),
        "application_url": "https://rurban.gov.in",
        "deadline": "2026-03-31",
        "source_name": "Rurban Mission Portal",
        "source_url": "https://rurban.gov.in",
        "last_verified_date": "2025-03-01",
        "kb_version": "2025-Q2-v2",
        "office_address": "District Collector / DRDAs",
        "office_contact": "011-23383312",
    },
]


def seed_additional_schemes() -> None:
    from models.scheme import Scheme
    from app.extensions import db

    existing = {s.name for s in Scheme.query.all()}
    added = 0
    skipped = 0
    for s_data in ADDITIONAL_SCHEMES:
        if s_data["name"] not in existing:
            scheme = Scheme(
                id=_uuid(),
                created_at=_now(),
                updated_at=_now(),
                is_active=1,
                **s_data,
            )
            db.session.add(scheme)
            added += 1
        else:
            skipped += 1

    db.session.commit()
    print(f"Additional schemes: {added} added, {skipped} already existed")
    logger.info("Additional schemes seeded: %d added, %d skipped", added, skipped)


if __name__ == "__main__":
    import os
    import sys
    from dotenv import load_dotenv

    sys.path.insert(0, os.path.dirname(__file__))
    load_dotenv()
    from app import create_app

    logging.basicConfig(level=logging.INFO)
    app = create_app()
    with app.app_context():
        seed_additional_schemes()
