-- ============================================================
-- BharatSeva AI — v1 Database Schema
-- ============================================================
-- Purpose:   Canonical CREATE TABLE statements for every table
--            used by the application in Phase 1 (SQLite dialect,
--            compatible with PostgreSQL with trivial changes noted).
-- Version:   1.0
-- Notes:
--   • All IDs are TEXT UUID v4 generated by the application layer,
--     not auto-increment integers.  This makes rows portable across
--     SQLite → PostgreSQL without ID collisions.
--   • Timestamps are TEXT ISO-8601 in SQLite.
--     In PostgreSQL change TEXT → TIMESTAMPTZ and use NOW().
--   • JSON columns are TEXT in SQLite.
--     In PostgreSQL change TEXT → JSONB for indexing and operators.
--   • Enums (role, verdict, status, etc.) are TEXT + CHECK constraints
--     so the role list can be extended (e.g. csc_operator) without
--     an ALTER TABLE / migration.
-- ============================================================

PRAGMA foreign_keys = ON;


-- ------------------------------------------------------------
-- 1. USERS
-- Stores authentication credentials and role only.
-- All personal/profile data is in citizen_profiles.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id              TEXT PRIMARY KEY,          -- UUID v4
    email           TEXT NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,             -- bcrypt, cost >= 12
    role            TEXT NOT NULL DEFAULT 'citizen'
                        CHECK (role IN ('citizen', 'admin', 'csc_operator')),
    is_active       INTEGER NOT NULL DEFAULT 1, -- 0 = soft-deleted / suspended
    created_at      TEXT NOT NULL,             -- ISO-8601
    updated_at      TEXT NOT NULL
);

-- Refresh tokens stored server-side for revocation support.
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id              TEXT PRIMARY KEY,          -- UUID v4
    user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash      TEXT NOT NULL UNIQUE,      -- SHA-256 of the raw token
    expires_at      TEXT NOT NULL,             -- ISO-8601
    revoked         INTEGER NOT NULL DEFAULT 0,
    created_at      TEXT NOT NULL
);

-- Password reset tokens (stub email flow; 1-hour TTL enforced by app).
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash      TEXT NOT NULL UNIQUE,
    expires_at      TEXT NOT NULL,
    used            INTEGER NOT NULL DEFAULT 0,
    created_at      TEXT NOT NULL
);


-- ------------------------------------------------------------
-- 2. CITIZEN PROFILES
-- One row per user; drives all eligibility and recommendations.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS citizen_profiles (
    user_id             TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    full_name           TEXT,
    state               TEXT,                  -- e.g. "Bihar", "Tamil Nadu"
    district            TEXT,
    occupation          TEXT,                  -- e.g. "farmer", "student", "msme_owner"
    income_band         TEXT,                  -- e.g. "below_1L", "1L_3L", "above_8L"
    category            TEXT                   -- "general", "obc", "sc", "st", "ews"
                            CHECK (category IN ('general','obc','sc','st','ews') OR category IS NULL),
    age                 INTEGER,
    gender              TEXT
                            CHECK (gender IN ('male','female','transgender','prefer_not_to_say') OR gender IS NULL),
    disability_status   TEXT                   -- "none", "locomotor", "visual", "hearing", "intellectual", "other"
                            CHECK (disability_status IN ('none','locomotor','visual','hearing','intellectual','other') OR disability_status IS NULL),
    education_level     TEXT,                  -- "none","primary","secondary","graduate","postgraduate"
    preferred_language  TEXT NOT NULL DEFAULT 'en',
    -- MSME / Startup specific (NULL for non-applicable personas)
    business_type       TEXT,                  -- "sole_proprietor", "partnership", "pvt_ltd", etc.
    business_sector     TEXT,
    udyam_number        TEXT,
    dpiit_recognised    INTEGER,               -- 0 / 1 (boolean for startup recognition)
    -- CSC operator context (NULL for self-service citizens)
    operator_id         TEXT REFERENCES users(id) ON DELETE SET NULL,
    -- Completeness tracking (computed by app, stored for dashboard)
    profile_completeness_pct INTEGER NOT NULL DEFAULT 0,
    created_at          TEXT NOT NULL,
    updated_at          TEXT NOT NULL
);


-- ------------------------------------------------------------
-- 3. SCHEMES (Knowledge Base)
-- Master scheme records; populated by KB ingestion scripts.
-- kb_version ties each record to a specific KB ingest run.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schemes (
    id                      TEXT PRIMARY KEY,  -- UUID v4 (stable across KB versions)
    name                    TEXT NOT NULL,
    name_hi                 TEXT,              -- Hindi name (from KB)
    category                TEXT NOT NULL,     -- "farmer","scholarship","senior_citizen",
                                               -- "women","disability","startup","msme","other"
    state_or_all_india      TEXT NOT NULL,     -- 2-letter state code or "ALL_INDIA"
    description             TEXT NOT NULL,
    description_hi          TEXT,              -- Hindi description
    eligibility_rules_json  TEXT NOT NULL,     -- structured rules for rule-based fallback
                                               -- see ai/knowledge_base/eligibility_rules/ for schema
    required_documents_json TEXT NOT NULL,     -- list of {name, description, mandatory: bool}
    application_url         TEXT,
    deadline                TEXT,              -- ISO-8601 date or NULL for rolling
    source_name             TEXT NOT NULL,
    source_url              TEXT NOT NULL,
    last_verified_date      TEXT NOT NULL,
    kb_version              TEXT NOT NULL,     -- e.g. "2025-Q2-v1"
    office_address          TEXT,
    office_contact          TEXT,
    is_active               INTEGER NOT NULL DEFAULT 1,
    created_at              TEXT NOT NULL,
    updated_at              TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_schemes_category   ON schemes(category);
CREATE INDEX IF NOT EXISTS idx_schemes_state       ON schemes(state_or_all_india);
CREATE INDEX IF NOT EXISTS idx_schemes_deadline    ON schemes(deadline);


-- ------------------------------------------------------------
-- 4. SAVED SCHEMES
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS saved_schemes (
    id          TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scheme_id   TEXT NOT NULL REFERENCES schemes(id) ON DELETE CASCADE,
    saved_at    TEXT NOT NULL,
    UNIQUE (user_id, scheme_id)
);

CREATE INDEX IF NOT EXISTS idx_saved_schemes_user ON saved_schemes(user_id);


-- ------------------------------------------------------------
-- 5. ELIGIBILITY CHECKS  (immutable audit log)
-- Rows are NEVER updated or deleted.
-- Every check by an agent writes a new row.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS eligibility_checks (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scheme_id       TEXT NOT NULL REFERENCES schemes(id) ON DELETE CASCADE,
    verdict         TEXT NOT NULL
                        CHECK (verdict IN ('ELIGIBLE','NOT_ELIGIBLE','PARTIALLY_ELIGIBLE')),
    confidence_score REAL NOT NULL                -- 0.0 – 1.0
                        CHECK (confidence_score >= 0.0 AND confidence_score <= 1.0),
    reasoning       TEXT NOT NULL,               -- plain-language explanation
    sources_json    TEXT NOT NULL,               -- [{name, url, kb_version, excerpt}]
    fallback_used   INTEGER NOT NULL DEFAULT 0,
    agent_log_id    TEXT REFERENCES agent_logs(id), -- backlink to agent execution
    checked_at      TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_elig_user   ON eligibility_checks(user_id);
CREATE INDEX IF NOT EXISTS idx_elig_scheme ON eligibility_checks(scheme_id);


-- ------------------------------------------------------------
-- 6. CITIZEN GOALS  (AI Copilot)
-- One row per goal submission; status transitions are tracked.
-- generated_plan_json is IMMUTABLE once written.
-- A revised plan creates a NEW row; old row archived.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS citizen_goals (
    id                  TEXT PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    goal_text           TEXT NOT NULL,           -- raw free-text goal from citizen
    goal_text_normalised TEXT,                   -- app-normalised / translated to English
    generated_plan_json TEXT,                    -- structured plan (see Journey B schema)
    plan_confidence     REAL                     -- overall confidence for the plan
                            CHECK (plan_confidence IS NULL OR
                                   (plan_confidence >= 0.0 AND plan_confidence <= 1.0)),
    status              TEXT NOT NULL DEFAULT 'DRAFT'
                            CHECK (status IN ('DRAFT','ACTIVE','COMPLETED','ARCHIVED')),
    agent_log_id        TEXT REFERENCES agent_logs(id),
    created_at          TEXT NOT NULL,
    updated_at          TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_goals_user   ON citizen_goals(user_id);
CREATE INDEX IF NOT EXISTS idx_goals_status ON citizen_goals(status);


-- ------------------------------------------------------------
-- 7. APPLICATIONS  (Tracker)
-- status_history_json is an append-only array:
-- [{status, changed_at, note}] — app layer enforces append-only.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS applications (
    id                  TEXT PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scheme_id           TEXT NOT NULL REFERENCES schemes(id) ON DELETE CASCADE,
    goal_id             TEXT REFERENCES citizen_goals(id) ON DELETE SET NULL,
    status              TEXT NOT NULL DEFAULT 'NOT_STARTED'
                            CHECK (status IN (
                                'NOT_STARTED','IN_PROGRESS','SUBMITTED',
                                'APPROVED','REJECTED'
                            )),
    status_history_json TEXT NOT NULL DEFAULT '[]', -- append-only history array
    created_at          TEXT NOT NULL,
    updated_at          TEXT NOT NULL,
    UNIQUE (user_id, scheme_id)
);

CREATE INDEX IF NOT EXISTS idx_apps_user   ON applications(user_id);
CREATE INDEX IF NOT EXISTS idx_apps_status ON applications(status);


-- ------------------------------------------------------------
-- 8. DOCUMENTS  (Vault)
-- Stores metadata and AI extraction results.
-- Raw files stored on filesystem / object store (path = file_path).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS documents (
    id                          TEXT PRIMARY KEY,
    user_id                     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scheme_id                   TEXT REFERENCES schemes(id) ON DELETE SET NULL, -- optional link
    filename                    TEXT NOT NULL,
    file_path                   TEXT NOT NULL,   -- server-side storage path
    mime_type                   TEXT NOT NULL,
    file_size_bytes             INTEGER NOT NULL,
    category                    TEXT,            -- "aadhaar","income_cert","land_record", etc.
    extracted_text              TEXT,            -- Granite OCR / extraction output
    ai_explanation              TEXT,            -- plain-language explanation from Granite
    verified_against_requirement TEXT            -- "VERIFIED","MISMATCH","UNREADABLE","PENDING"
                                    CHECK (verified_against_requirement IN (
                                        'VERIFIED','MISMATCH','UNREADABLE','PENDING'
                                    ) OR verified_against_requirement IS NULL),
    agent_log_id                TEXT REFERENCES agent_logs(id),
    uploaded_at                 TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_docs_user ON documents(user_id);


-- ------------------------------------------------------------
-- 9. CHAT HISTORY
-- Every message (citizen + AI) stored for history and analytics.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_history (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role            TEXT NOT NULL CHECK (role IN ('user','assistant','system')),
    message         TEXT NOT NULL,
    agent_used      TEXT,            -- which agent produced this reply (NULL for user turns)
    confidence_score REAL
                        CHECK (confidence_score IS NULL OR
                               (confidence_score >= 0.0 AND confidence_score <= 1.0)),
    sources_json    TEXT,            -- [{name, url, excerpt}]
    fallback_used   INTEGER NOT NULL DEFAULT 0,
    language        TEXT NOT NULL DEFAULT 'en',
    created_at      TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_chat_user ON chat_history(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_created ON chat_history(created_at);


-- ------------------------------------------------------------
-- 10. NOTIFICATIONS
-- priority: HIGH / MEDIUM / LOW drives UI badge colour.
-- related_date is the deadline or event date (for sorting).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
    id                  TEXT PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message             TEXT NOT NULL,
    message_hi          TEXT,                   -- Hindi translation
    type                TEXT NOT NULL           -- "deadline_reminder","status_change","info"
                            CHECK (type IN ('deadline_reminder','status_change','info','system')),
    priority            TEXT NOT NULL DEFAULT 'MEDIUM'
                            CHECK (priority IN ('HIGH','MEDIUM','LOW')),
    related_date        TEXT,                   -- ISO-8601 date of the event
    related_scheme_id   TEXT REFERENCES schemes(id) ON DELETE SET NULL,
    related_goal_id     TEXT REFERENCES citizen_goals(id) ON DELETE SET NULL,
    read                INTEGER NOT NULL DEFAULT 0,
    created_at          TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_notif_user      ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notif_unread    ON notifications(user_id, read);
CREATE INDEX IF NOT EXISTS idx_notif_related   ON notifications(related_date);


-- ------------------------------------------------------------
-- 11. AGENT LOGS  (immutable audit / Admin Portal source)
-- Rows are NEVER updated or deleted.
-- Written by the Orchestrator for EVERY agent invocation.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_logs (
    id              TEXT PRIMARY KEY,
    request_id      TEXT NOT NULL,              -- X-Request-ID from HTTP layer
    agent_name      TEXT NOT NULL,
    input_json      TEXT NOT NULL,              -- sanitised agent input (PII redacted for logs)
    output_json     TEXT NOT NULL,              -- full AgentResponse JSON
    confidence      REAL
                        CHECK (confidence IS NULL OR
                               (confidence >= 0.0 AND confidence <= 1.0)),
    latency_ms      INTEGER NOT NULL,
    fallback_used   INTEGER NOT NULL DEFAULT 0,
    fallback_reason TEXT,
    escalated_to    TEXT,                       -- agent name if escalated
    user_id         TEXT REFERENCES users(id) ON DELETE SET NULL, -- NULL for anonymous calls
    created_at      TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_alog_agent      ON agent_logs(agent_name);
CREATE INDEX IF NOT EXISTS idx_alog_request    ON agent_logs(request_id);
CREATE INDEX IF NOT EXISTS idx_alog_created    ON agent_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_alog_fallback   ON agent_logs(fallback_used);


-- ------------------------------------------------------------
-- 12. FEATURE FLAGS
-- Changeable at runtime via admin API — no redeploy required.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS feature_flags (
    id          TEXT PRIMARY KEY,
    flag_name   TEXT NOT NULL UNIQUE,
    enabled     INTEGER NOT NULL DEFAULT 0,
    description TEXT NOT NULL,
    updated_at  TEXT NOT NULL,
    updated_by  TEXT REFERENCES users(id) ON DELETE SET NULL
);

-- Seed initial flags (application layer inserts these on first run)
-- INSERT INTO feature_flags(id, flag_name, enabled, description, updated_at)
-- VALUES
--   ('ff-001', 'ai_copilot',          0, 'AI Citizen Copilot goal-planning feature',     datetime('now')),
--   ('ff-002', 'document_ai',         0, 'AI document extraction and verification',      datetime('now')),
--   ('ff-003', 'multilingual_ai',     1, 'Auto-translate AI responses to user language', datetime('now')),
--   ('ff-004', 'semantic_search',     0, 'Enable embedding-based semantic scheme search', datetime('now')),
--   ('ff-005', 'proactive_reminders', 0, 'Proactive deadline reminders via scheduler',   datetime('now'));


-- ------------------------------------------------------------
-- 13. KB SOURCES  (Knowledge Base provenance)
-- Tracks every source document ingested into the vector store.
-- Powers the Admin Portal "KB freshness" panel.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS kb_sources (
    id                  TEXT PRIMARY KEY,
    source_name         TEXT NOT NULL,
    source_url          TEXT NOT NULL,
    category            TEXT NOT NULL,
    state_or_all_india  TEXT NOT NULL DEFAULT 'ALL_INDIA',
    last_verified_date  TEXT NOT NULL,   -- ISO-8601 date
    version             TEXT NOT NULL,   -- e.g. "2025-Q2-v1"
    document_count      INTEGER NOT NULL DEFAULT 0,
    ingest_status       TEXT NOT NULL DEFAULT 'PENDING'
                            CHECK (ingest_status IN ('PENDING','INGESTED','FAILED','STALE')),
    created_at          TEXT NOT NULL,
    updated_at          TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_kbs_category ON kb_sources(category);
CREATE INDEX IF NOT EXISTS idx_kbs_verified ON kb_sources(last_verified_date);


-- ============================================================
-- END OF SCHEMA
-- ============================================================
